---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: triggers
  namespace: tekton-dream
rules:
- apiGroups:
    - sources.eventing.knative.dev
  resources:
  - containersources
  verbs:
  - get
  - list
  - create
  - update
  - delete
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: triggers
  namespace: tekton-dream
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: triggers
  namespace: tekton-dream
subjects:
  - kind: ServiceAccount
    name: triggers
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: triggers
