apiVersion: sources.eventing.knative.dev/v1alpha1
kind: ContainerSource
metadata:
  namespace: tekton-dream
  name: demo-event-source
spec:
  template:
    spec:
      containers:
        - image: "github.com/iancoffey/brokers-tekton/cmd/sendevent"
          name: demo-event
          args:
            - "--event-type"
            - "com.github.push"
            - "--source"
            - "demo-folks"
            - "--data"
            - "{\"repo\": \"iancoffey/ulmaceae\", \"sha\": \"6c81db31fcebb28cd60af3c715f83ad6d5a81d50\"}"
  sink:
    apiVersion: eventing.knative.dev/v1alpha1
    kind: Broker
    name: ci-builds
    namespace: tekton-dream
