apiVersion: tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: tekton-dream-triggertemplate
  namespace: tekton-dream
spec:
  params:
    - name: gitrevision
      description: The git revision
      default: master
    - name: gitrepositoryurl
      description: The git repository url
  resourcetemplates:
    - apiVersion: tekton.dev/v1alpha1
      kind: PipelineResource
      metadata:
        name: source-repo-$(uid)
        namespace: tekton-dream
      spec:
        type: git
        params:
        - name: revision
          value: $(params.gitrevision)
        - name: url
          value: $(params.gitrepositoryurl)
    - apiVersion: tekton.dev/v1alpha1
      kind: PipelineResource
      metadata:
        name: image-source-$(uid)
        namespace: $(params.namespace)
      spec:
        type: image
        params:
          - name: url
            value: docker.io/iancoffey # docker-repo-location.com/repo:getting-started
    - apiVersion: tekton.dev/v1alpha1
      kind: PipelineRun
      metadata:
        name: tekton-dream-pipeline-run
        namespace: $(params.namespace)
      spec:
        serviceAccountName: triggers-admin
        pipelineRef:
          name: tekton-dream-pipeline
        resources:
          - name: source-repo
            resourceRef:
              name: source-repo-$(uid)
          - name: image-source
            resourceRef:
              name: image-source-$(uid)
---
apiVersion: tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: tekton-dream-pipelinebinding
  namespace: tekton-dream
spec:
  params:
    - name: gitrevision
      value: $(body.sha)
    - name: namespace
      value: tekton-dream
    - name: gitrepositoryurl
      value: "https://github.com/$(body.repo)"
---
apiVersion: tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: tekton-dream-listener
  namespace: tekton-dream
spec:
  ServiceType: LoadBalancer
  serviceAccountName: triggers-admin
  triggers:
    - name: tekton-dram
      bindings:
      - name: tekton-dream-pipelinebinding
      template:
        name: tekton-dream-triggertemplate
